import React, { useEffect, useState } from 'react';
import { getOrganizationSettings, runExpenseReminderScan, saveOrganizationSettings } from '../../lib/supabase';

export default function ExpenseReminderSettings({ organizationId, onScanComplete }) {
  const [form, setForm] = useState({ receipt_reminder_enabled: true, receipt_reminder_first_after_days: 3, receipt_reminder_repeat_days: 3, receipt_reminder_max_count: 3 });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (!organizationId) return; getOrganizationSettings(organizationId).then(data => setForm(current => ({ ...current, ...(data || {}) }))).catch(error => setMessage(error.message || '알림 설정을 불러오지 못했습니다.')); }, [organizationId]);
  const field = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const save = async event => { event.preventDefault(); setBusy(true); try { await saveOrganizationSettings({ organization_id: organizationId, receipt_reminder_enabled: Boolean(form.receipt_reminder_enabled), receipt_reminder_first_after_days: Number(form.receipt_reminder_first_after_days), receipt_reminder_repeat_days: Number(form.receipt_reminder_repeat_days), receipt_reminder_max_count: Number(form.receipt_reminder_max_count) }); setMessage('영수증 미제출 알림 기준을 저장했어요.'); } catch (error) { setMessage(error.message || '알림 설정을 저장하지 못했습니다.'); } finally { setBusy(false); } };
  const scan = async () => { setBusy(true); try { const result = await runExpenseReminderScan(organizationId); setMessage(`현재 카드 내역을 확인해 새 알림 ${result.created || 0}건을 생성했어요.`); onScanComplete?.(); } catch (error) { setMessage(error.message || '미제출 내역을 확인하지 못했습니다.'); } finally { setBusy(false); } };
  return <section className="card full-card expense-reminder-settings"><div className="card-title"><div><h2>영수증 미제출 알림</h2><p>카드 사용 후 증빙이 없을 때 담당 직원에게 자동으로 알려 관리자 확인 업무를 줄입니다.</p></div><label className="switch-row"><input type="checkbox" checked={Boolean(form.receipt_reminder_enabled)} onChange={event => field('receipt_reminder_enabled', event.target.checked)}/><span>{form.receipt_reminder_enabled ? '자동 알림 사용' : '자동 알림 중지'}</span></label></div><form onSubmit={save}><div className="settings-input-grid"><label>첫 알림 시점<select value={form.receipt_reminder_first_after_days} onChange={event => field('receipt_reminder_first_after_days', event.target.value)} disabled={!form.receipt_reminder_enabled}>{[1,2,3,5,7].map(day => <option value={day} key={day}>승인 {day}일 후</option>)}</select></label><label>반복 주기<select value={form.receipt_reminder_repeat_days} onChange={event => field('receipt_reminder_repeat_days', event.target.value)} disabled={!form.receipt_reminder_enabled}>{[1,2,3,5,7,14].map(day => <option value={day} key={day}>{day}일 간격</option>)}</select></label><label>최대 알림 횟수<select value={form.receipt_reminder_max_count} onChange={event => field('receipt_reminder_max_count', event.target.value)} disabled={!form.receipt_reminder_enabled}>{[1,2,3,4,5].map(count => <option value={count} key={count}>최대 {count}회</option>)}</select></label></div><div className="expense-reminder-actions"><button className="submit" disabled={busy}>{busy ? '처리 중…' : '알림 기준 저장'}</button><button type="button" className="outline" disabled={busy || !form.receipt_reminder_enabled} onClick={scan}>지금 미제출 확인</button></div></form>{message && <p className={/못/.test(message) ? 'settings-help error' : 'settings-help'}>{message}</p>}</section>;
}
