import React, { useState } from 'react';
import { createManualExpense } from '../../lib/supabase';
import ExpenseLedgerExport from './ExpenseLedgerExport';

export default function ManualExpenseForm({ organizationId, employees = [], onSaved }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [duplicatePayload, setDuplicatePayload] = useState(null);
  const submit = async (event, allowDuplicate = false) => {
    event?.preventDefault();
    const payload = allowDuplicate ? duplicatePayload : (() => { const form = new FormData(event.currentTarget); return { organizationId, transactionDate: form.get('transactionDate'), merchantName: form.get('merchantName'), totalAmount: form.get('totalAmount'), supplyAmount: form.get('supplyAmount'), vatAmount: form.get('vatAmount'), category: form.get('category'), reason: form.get('reason'), staffId: form.get('staffId') || null }; })();
    setSaving(true); setMessage('');
    try { await createManualExpense({ ...payload, allowDuplicate }); setDuplicatePayload(null); event?.currentTarget?.reset(); setMessage('직접 지출을 등록하고 대시보드에 반영했어요.'); window.dispatchEvent(new CustomEvent('timefit-expense-created')); onSaved?.(); }
    catch (error) { if (/같은 날짜/.test(error.message || '')) { setDuplicatePayload(payload); setMessage('같은 날짜·사용처·금액의 지출이 이미 있습니다. 별도 지출인지 확인해 주세요.'); } else setMessage(error.message || '직접 지출을 등록하지 못했습니다.'); }
    finally { setSaving(false); }
  };
  return <><ExpenseLedgerExport organizationId={organizationId}/><section className="card full-card manual-expense-card"><div className="card-title"><div><h2>카드 외 지출</h2><p>현금, 계좌이체, 임차료 등 카드 내역이 없는 지출을 원장에 직접 등록합니다.</p></div><button className="outline" onClick={() => { setOpen(value => !value); setDuplicatePayload(null); setMessage(''); }}>{open ? '등록 닫기' : '+ 직접 지출 등록'}</button></div>{open && <form className="manual-expense-form" onSubmit={submit}><div className="settings-input-grid"><label>거래일<input name="transactionDate" type="date" required defaultValue={new Date().toLocaleDateString('en-CA')}/></label><label>사용처<input name="merchantName" required maxLength="120" placeholder="예: 건물 임대인"/></label><label>총금액<input name="totalAmount" type="number" min="1" step="1" required/></label><label>공급가액<input name="supplyAmount" type="number" min="0" step="1" placeholder="선택 입력"/></label><label>부가세<input name="vatAmount" type="number" min="0" step="1" placeholder="선택 입력"/></label><label>분류<select name="category" required><option value="">선택</option>{['재료비','소모품비','교통비','접대비','공과금','임차료','기타'].map(item => <option key={item}>{item}</option>)}</select></label><label>담당 직원<select name="staffId"><option value="">담당 없음</option>{employees.map(employee => <option key={employee.id} value={employee.id}>{employee.name} · {employee.team}</option>)}</select></label><label>지출 사유<input name="reason" maxLength="300" placeholder="예: 9월 임차료 계좌이체"/></label></div><p className="settings-help">공급가액과 부가세는 둘 다 입력하거나 둘 다 비워 주세요. 입력 시 합계가 총금액과 같아야 합니다.</p><div className="manual-expense-actions"><button className="submit" disabled={saving}>{saving ? '등록 중…' : '확정 지출로 등록'}</button>{duplicatePayload && <button type="button" className="outline danger-outline" disabled={saving} onClick={() => submit(null, true)}>중복 허용하고 별도 등록</button>}</div>{message && <p className={duplicatePayload ? 'settings-help error' : 'settings-help'}>{message}</p>}</form>}</section></>;
}
