import React, { useState } from 'react';

const won = value => `${Math.round(Number(value) || 0).toLocaleString('ko-KR')}원`;

export default function ProfitSummaryTable({ report, onOpenLedger }) {
  const [showAll, setShowAll] = useState(false);
  const rows = report?.displaySeries || report?.series || [];
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul' }).format(new Date());
  const completedRows = rows.filter(row => String(row.date).length === 7 || row.date <= today);
  const firstForecast = rows.findIndex(row => row.dataStatus === 'forecast');
  const aroundCutoff = firstForecast < 0 ? (completedRows.length ? completedRows : rows).slice(-10) : rows.slice(Math.max(0, firstForecast - 5), firstForecast + 5);
  const visibleRows = showAll ? rows : aroundCutoff;
  const cutoffPending = report?.salesCutoff && report.salesCutoff.status !== 'ready';
  const max = Math.max(1, ...visibleRows.map(row => Math.abs(Number(row.operatingProfit || 0))));
  const status = report?.audit?.status === 'closed' ? ['closed', '마감'] : report?.completeness?.cardSyncHealthy === false ? ['incomplete', '불완전'] : report?.completeness?.payrollComplete === false || report?.completeness?.reviewComplete === false || report?.completeness?.cardReconciliationComplete === false || Number(report?.totals?.provisionalCardExpenses || 0) > 0 ? ['provisional', '잠정 포함'] : ['confirmed', '확정 기준'];
  return <section className="finance-detail-table">
    <div className="finance-detail-title"><div><h3>기간별 손익표</h3><p>오늘까지의 실적과 이후 요일별 예상값을 같은 산식으로 비교합니다. 당일 매출은 오후 10시 수집 완료 후 확정합니다.</p></div><span className={`finance-data-status ${status[0]}`}>{status[1]}</span></div>
    <div className="finance-detail-scroll"><div className="finance-detail-head"><span>기간</span><span>순매출<small>실적 / 예상</small></span><span>운영지출<small>네 항목 합계</small></span><span>증빙 확정<small>지출 원장</small></span><span>미증빙 카드<small>잠정 반영</small></span><span>예상 변동지출<small>실제 비율</small></span><span>자동 계산<small>수수료 + 임대료</small></span><span>인건비<small>급여 초안 배분</small></span><span>운영순익<small>매출-지출-인건비</small></span><span>순익률</span></div>{visibleRows.map(row => { const pendingToday = cutoffPending && row.date === report.salesCutoff.date; const margin = pendingToday ? null : row.sales ? Math.round(row.operatingProfit / row.sales * 1000) / 10 : null; const open = () => row.dataStatus !== 'forecast' && onOpenLedger?.(String(row.date).length === 7 ? `${row.date}-01` : row.date); const statusLabel = pendingToday ? '22시 수집 대기' : row.dataStatus === 'forecast' ? '예상' : row.dataStatus === 'in_progress' ? '진행 중' : '실적'; return <article className={`${row.operatingProfit < 0 ? 'negative ' : ''}${row.dataStatus === 'forecast' ? 'forecast ' : ''}${onOpenLedger && row.dataStatus !== 'forecast' ? 'clickable' : ''}`} key={row.date} role={onOpenLedger && row.dataStatus !== 'forecast' ? 'button' : undefined} tabIndex={onOpenLedger && row.dataStatus !== 'forecast' ? 0 : undefined} onClick={open} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') open(); }}><span><b>{row.date}</b><small><em className={`finance-row-status ${row.dataStatus}`}>{statusLabel}</em> 주문 {row.orderCount ?? 0}건</small></span><span className="finance-value-cell"><b>{won(row.sales)}</b><small>{row.dataStatus === 'forecast' ? '요일별 평균 매출' : '완료 주문 매출'}</small></span><span className="finance-value-cell"><b>{won(row.operatingExpenses)}</b><small>{won(row.confirmedExpenses)} + {won(row.provisionalCardExpenses)} + {won(row.forecastExpenses)} + {won(row.calculatedExpenses)}</small></span><span className="finance-value-cell"><b>{won(row.confirmedExpenses)}</b><small>확정 처리 금액</small></span><span className="finance-value-cell"><b>{won(row.provisionalCardExpenses)}</b><small>영수증 미첨부</small></span><span className="finance-value-cell"><b>{won(row.forecastExpenses)}</b><small>{row.dataStatus === 'forecast' ? '실적 변동비율 적용' : '-'}</small></span><span className="finance-value-cell"><b>{won(row.calculatedExpenses)}</b><small>수수료 {won(row.cardFees)} · 임대료 {won(row.rentExpense)}</small></span><span className="finance-value-cell"><b>{won(row.laborCost)}</b><small>근태 기준 일별 배분</small></span><strong>{pendingToday ? '집계 대기' : <><i style={{ width: `${Math.abs(Number(row.operatingProfit || 0)) / max * 100}%` }}/>{won(row.operatingProfit)}</>}</strong><em>{margin === null ? '-' : `${margin}%`}</em></article>; })}</div>
    {rows.length > 10 && <button className="finance-table-more" type="button" onClick={() => setShowAll(value => !value)}>{showAll ? '최근 10개만 보기' : `전체 ${rows.length}개 기간 보기`}</button>}
  </section>;
}
