import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './modes.css';
import './mobile.css';
import './refinement.css';
import './feedback.css';
import './navigation.css';
import { recordQrAttendance, supabase } from './lib/supabase';

const today = '2026년 8월 9일 (일)';
const defaultEmployees = [
  { id: 1, name: '김민지', team: '운영팀', role: '매니저', pay: '월급제', state: '근무 중', time: '09:02', hours: '7시간 28분', color: 'purple' },
  { id: 2, name: '이준호', team: '매장팀', role: '바리스타', pay: '시급제', state: '근무 중', time: '09:00', hours: '7시간 30분', color: 'blue' },
  { id: 3, name: '박서연', team: '매장팀', role: '바리스타', pay: '시급제', state: '지각', time: '09:18', hours: '7시간 12분', color: 'orange' },
  { id: 4, name: '최도윤', team: '주방팀', role: '조리사', pay: '시급제', state: '미출근', time: '-', hours: '-', color: 'mint' },
  { id: 5, name: '한유진', team: '운영팀', role: '사원', pay: '월급제', state: '휴가', time: '-', hours: '연차 1일', color: 'pink' },
];

const nav = [
  ['dashboard', '홈', '⌂'], ['attendance', '출퇴근', '◷'], ['schedule', '스케줄', '▦'],
  ['leave', '휴가 · 연차', '◫'], ['payroll', '급여 관리', '₩'], ['employees', '직원 관리', '♙'],
];

const employeeNav = [
  ['employeeHome', '내 홈', '⌂'], ['mySchedule', '내 스케줄', '▦'], ['myAttendance', '출퇴근', '◷'], ['myLeave', '휴가', '◫'],
];

function Avatar({ name, color = 'blue' }) { return <span className={`avatar ${color}`}>{name[0]}</span>; }
function Chip({ children, type }) { return <span className={`chip ${type}`}>{children}</span>; }
function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onClick={onClose}><section className="modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>; }

function Dashboard({ employees, setModal, checkedIn, onSelect, onNavigate }) {
  const working = employees.filter(x => x.state === '근무 중').length + (checkedIn ? 1 : 0);
  return <>
    <div className="hero"><div><p className="date-label">{today}</p><h1>오늘, 매장은 잘 돌아가고 있나요?</h1><p>출퇴근부터 승인 요청까지 필요한 정보를 한 번에 확인하세요.</p></div><button className="cta" onClick={() => setModal('employee')}>직원 등록하기 <span>→</span></button></div>
    <section className="summary-grid">
      <article><p>오늘 출근</p><strong>{18 + (checkedIn ? 1 : 0)}<small>명</small></strong><span>전체 23명 중</span></article>
      <article><p>현재 근무 중</p><strong>{working + 12}<small>명</small></strong><span className="up">어제보다 2명 많아요</span></article>
      <article><p>확인 필요</p><strong className="warn">3<small>건</small></strong><span>지각 1 · 미출근 2</span></article>
      <article><p>이번 달 인건비</p><strong>₩24.8<small>M</small></strong><span>예상 급여 기준</span></article>
    </section>
    <div className="dashboard-layout">
      <section className="card live-card"><div className="card-title"><div><h2>실시간 출퇴근</h2><p>오늘 근무 예정 직원</p></div><button onClick={() => onNavigate('attendance')}>전체 보기</button></div>
        <div className="attendance-list">{employees.slice(0, 4).map(item => <div className="attendance-row clickable-row" key={item.id} onClick={() => onSelect(item)}><Avatar name={item.name} color={item.color}/><div className="grow"><b>{item.name}</b><span>{item.role} · {item.pay}</span></div><div className="time"><Chip type={item.state === '근무 중' ? 'green' : item.state === '지각' ? 'orange' : 'gray'}>{item.state}</Chip><b>{item.time}</b></div></div>)}</div>
      </section>
      <section className="card approval-card"><div className="card-title"><div><h2>승인할 일이 있어요</h2><p>빠르게 확인해 주세요.</p></div><span className="count">3</span></div>
        <button className="approval" onClick={() => setModal('leave')}><Avatar name="이준호" color="purple"/><span><b>이준호님의 연차 신청</b><small>8월 14일 · 연차 1일</small></span><i>›</i></button>
        <button className="approval" onClick={() => setModal('leave')}><Avatar name="박서연" color="orange"/><span><b>박서연님의 출퇴근 수정</b><small>8월 8일 · 출근 시간</small></span><i>›</i></button>
        <button className="approval" onClick={() => setModal('leave')}><Avatar name="최도윤" color="mint"/><span><b>최도윤님의 휴무 신청</b><small>8월 16일 · 주말 휴무</small></span><i>›</i></button>
      </section>
    </div>
    <section className="card weekly"><div className="card-title"><div><h2>이번 주 스케줄</h2><p>8월 9일 ~ 8월 15일</p></div><button onClick={() => onNavigate('schedule')}>스케줄 관리</button></div><div className="week">{['일\n9','월\n10','화\n11','수\n12','목\n13','금\n14','토\n15'].map((day, i) => <div className={i === 0 ? 'selected-day' : ''} key={day}><b>{day.split('\n')[0]} <small>{day.split('\n')[1]}</small></b><span>{i === 0 ? '18명 근무' : i === 5 ? '휴가 3건' : `${18 + (i % 4)}명 근무`}</span></div>)}</div></section>
  </>;
}

function Attendance({ employees, checkedIn, setCheckedIn, onSelect }) { const [filter, setFilter] = useState('전체'); return <><div className="page-title"><div><p>{today}</p><h1>출퇴근 관리</h1></div><button className={checkedIn ? 'checkin complete' : 'checkin'} onClick={() => setCheckedIn(!checkedIn)}>{checkedIn ? '✓ 출근 완료 · 퇴근하기' : '◷ 내 출근 기록하기'}</button></div><section className="card full-card"><div className="tabs">{['전체','근무 중','지각','미출근','휴가'].map(t => <button className={filter === t ? 'selected' : ''} onClick={() => setFilter(t)} key={t}>{t}</button>)}</div><div className="employee-table"><div className="table-head"><span>직원</span><span>상태</span><span>출근</span><span>근무 시간</span><span>관리</span></div>{employees.filter(e => filter === '전체' || e.state === filter).map(e => <div className="table-row clickable-row" key={e.id} onClick={() => onSelect(e)}><span className="name-cell"><Avatar name={e.name} color={e.color}/><b>{e.name}<small>{e.team} · {e.role}</small></b></span><span><Chip type={e.state === '근무 중' ? 'green' : e.state === '지각' ? 'orange' : 'gray'}>{e.state}</Chip></span><span>{e.time}</span><span>{e.hours}</span><button className="outline" onClick={(event) => { event.stopPropagation(); onSelect(e); }}>상세</button></div>)}</div></section></> }

function Schedule({ setModal, employees, onSelect }) {
  const days = [
    { id: '2026-08-09', weekday: '일', day: '9', label: '8월 9일 일요일' }, { id: '2026-08-10', weekday: '월', day: '10', label: '8월 10일 월요일' },
    { id: '2026-08-11', weekday: '화', day: '11', label: '8월 11일 화요일' }, { id: '2026-08-12', weekday: '수', day: '12', label: '8월 12일 수요일' },
    { id: '2026-08-13', weekday: '목', day: '13', label: '8월 13일 목요일' }, { id: '2026-08-14', weekday: '금', day: '14', label: '8월 14일 금요일' }, { id: '2026-08-15', weekday: '토', day: '15', label: '8월 15일 토요일' },
  ];
  const scheduleByDate = {
    '2026-08-09': [['김민지', '09:00 – 18:00', '오픈 근무'], ['이준호', '09:00 – 17:00', '오전 근무'], ['박서연', '10:00 – 19:00', '마감 근무'], ['최도윤', '휴무', '주휴일']],
    '2026-08-10': [['김민지', '09:00 – 18:00', '오픈 근무'], ['박서연', '09:00 – 17:00', '오전 근무'], ['한유진', '연차', '연차 휴가']],
    '2026-08-11': [['이준호', '12:00 – 20:00', '오후 근무'], ['최도윤', '10:00 – 19:00', '주방 근무'], ['박서연', '휴무', '휴무']],
    '2026-08-12': [['김민지', '09:00 – 18:00', '오픈 근무'], ['이준호', '휴무', '주휴일']],
    '2026-08-13': [['박서연', '10:00 – 19:00', '마감 근무'], ['최도윤', '10:00 – 19:00', '주방 근무']],
    '2026-08-14': [['김민지', '09:00 – 18:00', '오픈 근무'], ['이준호', '연차', '연차 휴가'], ['한유진', '연차', '연차 휴가']],
    '2026-08-15': [['박서연', '10:00 – 19:00', '마감 근무'], ['최도윤', '휴무', '주휴일']],
  };
  const [selectedDate, setSelectedDate] = useState('2026-08-09'); const [viewMode, setViewMode] = useState('day'); const selectedIndex = days.findIndex(day => day.id === selectedDate); const selectedDay = days[selectedIndex]; const shifts = scheduleByDate[selectedDate] || [];
  const changeDate = (offset) => { const next = days[selectedIndex + offset]; if (next) setSelectedDate(next.id); };
  const workCount = shifts.filter(([, time]) => time !== '휴무' && time !== '연차').length; const offCount = shifts.filter(([, time]) => time === '휴무').length; const leaveCount = shifts.filter(([, time]) => time === '연차').length;
  return <><div className="page-title"><div><p>2026년 8월 둘째 주</p><h1>스케줄</h1></div><button className="cta" onClick={() => setModal('schedule')}>+ 근무 추가</button></div><section className="card schedule-card"><div className="schedule-tools"><button onClick={() => changeDate(-1)} disabled={selectedIndex === 0}>‹</button><b>{viewMode === 'day' ? selectedDay.label : '8월 9일 ~ 8월 15일'}</b><button onClick={() => changeDate(1)} disabled={viewMode === 'week' || selectedIndex === days.length - 1}>›</button><span/><button className="outline" onClick={() => setViewMode(viewMode === 'day' ? 'week' : 'day')}>{viewMode === 'day' ? '주간 보기' : '일간 보기'}</button></div><div className="mobile-week-strip">{days.map(day => <button className={day.id === selectedDate ? 'active' : ''} onClick={() => { setSelectedDate(day.id); setViewMode('day'); }} key={day.id}><b>{day.weekday}</b><span>{day.day}</span></button>)}</div><div className="schedule-summary"><span>근무 <b>{workCount}명</b></span><span>휴무 <b>{offCount}명</b></span><span>연차 <b>{leaveCount}명</b></span></div>{viewMode === 'week' && <div className="weekly-schedule-board">{days.map(day => { const items = scheduleByDate[day.id] || []; return <button key={day.id} onClick={() => { setSelectedDate(day.id); setViewMode('day'); }}><b>{day.weekday} {day.day}</b><span>근무 {items.filter(([, time]) => time !== '휴무' && time !== '연차').length}명</span><small>휴무 {items.filter(([, time]) => time === '휴무').length} · 연차 {items.filter(([, time]) => time === '연차').length}</small></button>; })}</div>}<div className={`shift-list ${viewMode === 'week' ? 'hidden' : ''}`}>{shifts.length ? shifts.map(([name,time,label]) => { const employee = employees.find(item => item.name === name) || { name, color: 'blue' }; return <div className="shift clickable-row" key={`${selectedDate}-${name}`} onClick={() => onSelect(employee)}><Avatar name={name} color={employee.color}/><div className="grow"><b>{name}</b><small>{label}</small></div><div className="shift-time-block"><strong>{time}</strong><span>직원 상세 보기 ›</span></div><button className="ghost" onClick={(event) => { event.stopPropagation(); setModal('schedule'); }}>수정</button></div>; }) : <div className="empty-schedule"><b>등록된 근무가 없어요.</b><span>근무 추가 버튼으로 새 일정을 만들어 보세요.</span></div>}</div></section></>;
}

function Leave({ setModal, employees, onSelect }) { return <><div className="page-title"><div><p>2026년 기준</p><h1>휴가 · 연차 관리</h1></div><button className="cta" onClick={() => setModal('leave')}>+ 휴가 신청</button></div><section className="leave-overview"><div className="balance card"><p>내 연차 잔여</p><strong>8.5<small>일</small></strong><div><span>발생 15일</span><span>사용 6.5일</span></div><div className="progress"><i/></div></div><div className="card leave-info"><h2>승인 대기 중인 휴가</h2><p>총 2건의 요청을 확인해 주세요.</p><button onClick={() => setModal('leave')}>요청 확인하기 →</button></div></section><section className="card full-card"><div className="card-title"><div><h2>휴가 사용 내역</h2><p>최근 3개월</p></div></div>{[['8월 14일','연차','이준호','승인 대기'],['7월 28일','오후 반차','김민지','승인 완료'],['7월 18일','연차','한유진','승인 완료']].map(r => <div className="leave-row clickable-row" key={r.join()} onClick={() => onSelect(employees.find(item => item.name === r[2]))}><span><b>{r[0]}</b><small>{r[2]}</small></span><span>{r[1]}</span><Chip type={r[3] === '승인 완료' ? 'green' : 'orange'}>{r[3]}</Chip></div>)}</section></> }

function Payroll({ employees, onSelect }) { const downloadCsv = () => { const csv = ['직원,급여 형태,예상 급여,상태', '김민지,월급제,3200000,완료', '이준호,시급제,2148500,완료', '박서연,시급제,,근태 확인 필요'].join('\n'); const href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = href; link.download = 'timefit-2026-08-payroll.csv'; link.click(); URL.revokeObjectURL(href); }; return <><div className="page-title"><div><p>2026년 8월 급여</p><h1>급여 관리</h1></div><button className="cta">급여 마감하기</button></div><section className="pay-cards"><div className="card"><p>예상 총 인건비</p><strong>₩24,800,000</strong><span>전월 대비 <b>4.2% 증가</b></span></div><div className="card"><p>급여 산정 완료</p><strong>20 <small>/ 23명</small></strong><span>3명은 근태 확인이 필요해요.</span></div></section><section className="card full-card"><div className="card-title"><div><h2>직원별 급여 현황</h2><p>근태 데이터를 기준으로 계산된 예상액입니다.</p></div><button className="outline" onClick={downloadCsv}>CSV 다운로드</button></div>{[['김민지','월급제','₩3,200,000','완료'],['이준호','시급제','₩2,148,500','완료'],['박서연','시급제','산정 전','근태 확인 필요']].map(r => <div className="salary-row clickable-row" key={r[0]} onClick={() => onSelect(employees.find(item => item.name === r[0]))}><Avatar name={r[0]}/><b>{r[0]}</b><span>{r[1]}</span><strong>{r[2]}</strong><Chip type={r[3] === '완료' ? 'green' : 'orange'}>{r[3]}</Chip></div>)}</section></> }

function Employees({ employees, setModal, onSelect }) { return <><div className="page-title"><div><p>재직 23명</p><h1>직원 관리</h1></div><button className="cta" onClick={() => setModal('employee')}>+ 직원 등록</button></div><section className="card full-card"><div className="search">⌕ <input placeholder="이름, 부서, 직책으로 검색" /></div>{employees.map(e => <div className="employee-row clickable-row" key={e.id} onClick={() => onSelect(e)}><Avatar name={e.name} color={e.color}/><span className="grow"><b>{e.name}</b><small>{e.team} · {e.role}</small></span><span>{e.pay}</span><Chip type="green">재직</Chip><button className="outline" onClick={(event) => { event.stopPropagation(); onSelect(e); }}>상세</button></div>)}</section></> }

function EmployeeDetail({ employee, onBack, setModal, onNavigate }) {
  const profile = employee || defaultEmployees[0];
  const stateType = profile.state === '근무 중' ? 'green' : profile.state === '지각' ? 'orange' : 'gray';
  return <><div className="detail-back"><button onClick={onBack}>← 직원 목록</button></div><section className="employee-profile card"><div className="profile-main"><Avatar name={profile.name} color={profile.color}/><div><p>{profile.team} · {profile.role}</p><h1>{profile.name}</h1><span>{profile.pay} · 입사일 2025년 3월 1일</span></div></div><div className="profile-actions"><button className="outline">정보 수정</button><button className="cta" onClick={() => setModal('schedule')}>+ 근무 추가</button></div></section>
    <section className="employee-summary"><div className="card"><p>오늘 상태</p><strong><Chip type={stateType}>{profile.state}</Chip></strong><span>출근 {profile.time}</span></div><div className="card"><p>이번 달 근무시간</p><strong>142<small>시간</small></strong><span>예정 대비 96%</span></div><div className="card"><p>연차 잔여</p><strong>8.5<small>일</small></strong><span>발생 15일 · 사용 6.5일</span></div><div className="card"><p>이번 달 예상 급여</p><strong>₩2.15<small>M</small></strong><span>근태 반영 기준</span></div></section>
    <div className="employee-detail-grid"><section className="card"><div className="card-title"><div><h2>이번 주 근무 일정</h2><p>8월 9일 ~ 8월 15일</p></div><button onClick={() => onNavigate('schedule')}>전체 보기</button></div>{[['오늘','09:00 – 17:00','오전 근무'],['8월 10일 월','09:00 – 17:00','오전 근무'],['8월 11일 화','12:00 – 20:00','오후 근무'],['8월 12일 수','휴무','주휴일']].map(r => <div className="detail-row" key={r[0]}><b>{r[0]}</b><strong>{r[1]}</strong><span>{r[2]}</span></div>)}</section><section className="card"><div className="card-title"><div><h2>최근 연차 · 요청</h2><p>처리가 필요한 항목</p></div><button onClick={() => onNavigate('leave')}>전체 보기</button></div><div className="detail-leave"><b>8월 14일 금요일</b><span>연차 1일 신청</span><Chip type="orange">승인 대기</Chip></div><div className="detail-leave"><b>7월 22일 수요일</b><span>오후 반차</span><Chip type="green">승인 완료</Chip></div><div className="leave-balance"><span>연차 사용률</span><b>43%</b><div className="progress"><i/></div></div></section></div>
    <section className="card full-card"><div className="card-title"><div><h2>최근 출퇴근 기록</h2><p>실제 근무시간 기준</p></div><button onClick={() => onNavigate('attendance')}>전체 기록 보기</button></div>{[['8월 9일 일','09:00','근무 중','7시간 30분'],['8월 8일 토','09:01','퇴근 완료','7시간 29분'],['8월 7일 금','09:00','퇴근 완료','8시간'],['8월 6일 목','09:03','퇴근 완료','7시간 27분']].map(r => <div className="detail-attendance" key={r[0]}><b>{r[0]}</b><span>출근 {r[1]}</span><Chip type={r[2] === '근무 중' ? 'green' : 'gray'}>{r[2]}</Chip><strong>{r[3]}</strong></div>)}</section></>;
}

function EmployeeHome({ setActive, checkedIn, setCheckedIn }) {
  return <><div className="personal-hero"><div><p className="date-label">{today}</p><h1>안녕하세요, 이준호님 👋</h1><p>오늘도 좋은 하루 보내세요.</p></div><button className={checkedIn ? 'checkin complete' : 'checkin'} onClick={() => setCheckedIn(!checkedIn)}>{checkedIn ? '✓ 출근 완료' : '◷ 출근 기록'}</button></div>
    <section className="today-shift card"><div><div className="card-title"><div><p>오늘의 근무</p><h2>성수점 · 오전 근무</h2></div><Chip type="green">근무 중</Chip></div><div className="shift-time"><b>09:00</b><i/><b>17:00</b></div><div className="shift-meta"><span>예상 근무 7시간</span><span>휴게 1시간</span><button onClick={() => setActive('mySchedule')}>스케줄 보기 →</button></div></div></section>
    <div className="personal-grid"><section className="card mini-card"><p>이번 주 근무시간</p><strong>31시간 <small>30분</small></strong><span>예정 38시간 중 83%</span><div className="progress"><i/></div></section><section className="card mini-card"><p>남은 연차</p><strong>8.5<small>일</small></strong><span>올해 사용 6.5일</span><button className="link-button" onClick={() => setActive('myLeave')}>휴가 신청하기 →</button></section></div>
    <section className="card my-upcoming"><div className="card-title"><div><h2>다가오는 내 일정</h2><p>이번 주 스케줄</p></div><button onClick={() => setActive('mySchedule')}>전체 보기</button></div>{[['8월 10일 월','09:00 – 17:00','오전 근무'],['8월 11일 화','12:00 – 20:00','오후 근무'],['8월 12일 수','휴무','휴무']].map(([d,t,n]) => <div className="upcoming-row" key={d}><b>{d}</b><span>{n}</span><strong>{t}</strong></div>)}</section></>;
}

function MySchedule() { return <><div className="page-title"><div><p>이준호님의 일정</p><h1>내 스케줄</h1></div><button className="outline">2026년 8월 ▾</button></div><section className="card my-calendar"><div className="calendar-days">{['일','월','화','수','목','금','토'].map(day => <b key={day}>{day}</b>)}{Array.from({length: 31}, (_, index) => <div className={[9,10,11,14,15].includes(index) ? 'has-shift' : index === 12 ? 'day-off' : ''} key={index}><b>{index + 1}</b>{[9,10,11,14,15].includes(index) && <span>{index === 11 ? '12–20' : '09–17'}</span>}{index === 12 && <span>휴무</span>}</div>)}</div></section><section className="card full-card"><div className="card-title"><div><h2>등록된 근무 일정</h2><p>예정된 스케줄만 표시됩니다.</p></div></div>{[['8월 10일 월','09:00 – 17:00','성수점 · 오전 근무'],['8월 11일 화','12:00 – 20:00','성수점 · 오후 근무'],['8월 12일 수','휴무','주휴일'],['8월 13일 목','09:00 – 17:00','성수점 · 오전 근무']].map(r => <div className="my-schedule-row" key={r[0]}><b>{r[0]}</b><strong>{r[1]}</strong><span>{r[2]}</span></div>)}</section></> }

function QrAttendance({ checkedIn, setCheckedIn }) {
  const videoRef = useRef(null); const streamRef = useRef(null); const [isOpen, setOpen] = useState(false); const [cameraError, setCameraError] = useState(''); const [status, setStatus] = useState('매장 QR 코드를 카메라에 비춰 주세요.');
  const stopCamera = () => { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; };
  useEffect(() => () => stopCamera(), []);
  const completeAttendance = async (token, source = 'QR') => {
    const action = checkedIn ? 'check_out' : 'check_in';
    try {
      if (supabase && !token) throw new Error('실제 출퇴근은 유효한 매장 QR 코드가 필요합니다.');
      if (supabase && token) await recordQrAttendance({ token, action });
      setCheckedIn(!checkedIn); setStatus(`${source} 인증 완료 · ${checkedIn ? '퇴근' : '출근'} 처리됐어요.`);
    } catch (error) {
      setCameraError(error.message || '출퇴근 기록을 저장하지 못했습니다. 네트워크와 QR 유효 시간을 확인해 주세요.');
    }
  };
  const startCamera = async () => { setCameraError(''); setOpen(true); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } if ('BarcodeDetector' in window) { const detector = new window.BarcodeDetector({ formats: ['qr_code'] }); const scan = async () => { if (!videoRef.current || !streamRef.current) return; try { const result = await detector.detect(videoRef.current); if (result.length) { stopCamera(); setOpen(false); await completeAttendance(result[0].rawValue); return; } } catch (_) {} window.setTimeout(scan, 450); }; scan(); } else setStatus('카메라 촬영 후 하단 버튼으로 인증을 완료해 주세요.'); } catch (_) { setCameraError('카메라를 사용할 수 없습니다. 브라우저 권한을 허용한 뒤 다시 시도해 주세요.'); } };
  const completeByPhoto = async () => { stopCamera(); setOpen(false); await completeAttendance(null, '사진'); };
  return <section className="card qr-card"><div className="qr-icon">⌘</div><div><p>QR 출퇴근</p><h2>{checkedIn ? '퇴근할 시간이에요' : '매장 QR로 출근하기'}</h2><span>{status}</span></div><button className="cta" onClick={startCamera}>{checkedIn ? 'QR 퇴근' : 'QR 출근'}</button>{isOpen && <div className="scanner"><video ref={videoRef} muted playsInline/><div className="scan-frame"/><p>{cameraError || 'QR 코드를 찾는 중…'}</p><div><button className="outline" onClick={() => {stopCamera();setOpen(false)}}>닫기</button><button className="cta" onClick={completeByPhoto}>사진 인증 완료</button></div></div>}</section>;
}

function MyAttendance({ checkedIn, setCheckedIn }) { return <><div className="page-title"><div><p>{today}</p><h1>출퇴근</h1></div></div><QrAttendance checkedIn={checkedIn} setCheckedIn={setCheckedIn}/><section className="card full-card"><div className="card-title"><div><h2>이번 주 근무 기록</h2><p>내 실제 근무시간</p></div><strong className="total-hours">31시간 30분</strong></div>{[['8월 9일 일','09:00','근무 중','7시간 30분'],['8월 8일 토','09:01','퇴근 완료','7시간 29분'],['8월 7일 금','09:00','퇴근 완료','8시간'],['8월 6일 목','-','휴무','-']].map(r => <div className="attendance-history" key={r[0]}><b>{r[0]}</b><span>출근 {r[1]}</span><Chip type={r[2] === '근무 중' ? 'green' : 'gray'}>{r[2]}</Chip><strong>{r[3]}</strong></div>)}</section></> }

function MyLeave({ setModal }) { return <><div className="page-title"><div><p>이준호님의 휴가</p><h1>연차 · 휴가</h1></div><button className="cta" onClick={() => setModal('leaveRequest')}>+ 휴가 신청</button></div><section className="personal-grid"><div className="card mini-card"><p>연차 잔여</p><strong>8.5<small>일</small></strong><span>발생 15일 · 사용 6.5일</span><div className="progress"><i/></div></div><div className="card mini-card"><p>승인 대기</p><strong>1<small>건</small></strong><span>8월 14일 연차 신청</span></div></section><section className="card full-card"><div className="card-title"><div><h2>내 휴가 내역</h2><p>최근 신청 및 사용 내역</p></div></div>{[['8월 14일 금','연차 1일','승인 대기'],['7월 22일 수','오후 반차','승인 완료'],['6월 4일 목','연차 1일','승인 완료']].map(r => <div className="leave-row" key={r[0]}><span><b>{r[0]}</b><small>{r[1]}</small></span><span>개인 휴가</span><Chip type={r[2] === '승인 완료' ? 'green' : 'orange'}>{r[2]}</Chip></div>)}</section></> }

function App() {
  const [mode, setMode] = useState('manager'); const [active, setActive] = useState('dashboard'); const [employees, setEmployees] = useState(defaultEmployees); const [selectedEmployee, setSelectedEmployee] = useState(defaultEmployees[0]); const [modal, setModal] = useState(null); const [checkedIn, setCheckedIn] = useState(false); const [toast, setToast] = useState('');
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 2200); return () => clearTimeout(timer); }, [toast]);
  const openEmployeeDetail = (employee) => { setSelectedEmployee(employee); setActive('employeeDetail'); };
  const managerContent = { dashboard: <Dashboard employees={employees} setModal={setModal} checkedIn={checkedIn} onSelect={openEmployeeDetail} onNavigate={setActive}/>, attendance: <Attendance employees={employees} checkedIn={checkedIn} setCheckedIn={setCheckedIn} onSelect={openEmployeeDetail}/>, schedule: <Schedule setModal={setModal} employees={employees} onSelect={openEmployeeDetail}/>, leave: <Leave setModal={setModal} employees={employees} onSelect={openEmployeeDetail}/>, payroll: <Payroll employees={employees} onSelect={openEmployeeDetail}/>, employees: <Employees employees={employees} setModal={setModal} onSelect={openEmployeeDetail}/>, employeeDetail: <EmployeeDetail employee={selectedEmployee} onBack={() => setActive('employees')} setModal={setModal} onNavigate={setActive}/> };
  const employeeContent = { employeeHome: <EmployeeHome setActive={setActive} checkedIn={checkedIn} setCheckedIn={setCheckedIn}/>, mySchedule: <MySchedule/>, myAttendance: <MyAttendance checkedIn={checkedIn} setCheckedIn={setCheckedIn}/>, myLeave: <MyLeave setModal={setModal}/> };
  const currentNav = mode === 'manager' ? nav : employeeNav; const mobileNav = mode === 'manager' ? [...nav.slice(0, 3), ['more', '더보기', '⋯']] : employeeNav; const content = (mode === 'manager' ? managerContent : employeeContent)[active];
  const changeMode = (nextMode) => { setMode(nextMode); setActive(nextMode === 'manager' ? 'dashboard' : 'employeeHome'); setModal(null); };
  const saveEmployee = e => { e.preventDefault(); const data = new FormData(e.currentTarget); const name = data.get('name'); if (!name) return; setEmployees([...employees, { id: Date.now(), name, team: data.get('team') || '미정', role: data.get('role') || '직원', pay: data.get('pay'), state: '미출근', time: '-', hours: '-', color: 'blue' }]); setModal(null); setToast(`${name}님을 등록했어요.`); };
  const approve = () => { setModal(null); setToast('요청을 승인했어요.'); };
  return <div className={`app ${mode}`}><aside className="sidebar"><div className="brand"><span>✓</span><b>timefit</b></div><div className="mode-switch sidebar-switch"><button className={mode === 'manager' ? 'active' : ''} onClick={() => changeMode('manager')}>관리자</button><button className={mode === 'employee' ? 'active' : ''} onClick={() => changeMode('employee')}>직원</button></div><nav>{currentNav.map(([id,label,icon]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="store"><small>현재 {mode === 'manager' ? '사업장' : '계정'}</small><b>{mode === 'manager' ? '타임핏 성수점' : '이준호 · 바리스타'}</b><span>{mode === 'manager' ? '관리자 계정 · 김대표' : '직원 테스트 모드'}</span></div></aside><main><header><div className="header-brand"><span>✓</span><b>timefit</b></div><div className="header-mode mode-switch"><button className={mode === 'manager' ? 'active' : ''} onClick={() => changeMode('manager')}>관리자</button><button className={mode === 'employee' ? 'active' : ''} onClick={() => changeMode('employee')}>직원</button></div><span className="profile">{mode === 'manager' ? '김' : '이'}</span></header><div className="content">{content}</div></main><nav className="mobile-nav">{mobileNav.map(([id,label,icon]) => <button key={id} className={active === id || (id === 'more' && modal === 'more') ? 'active' : ''} onClick={() => id === 'more' ? setModal('more') : setActive(id)}><i>{icon}</i><span>{label.replace(' · 연차','')}</span></button>)}</nav>{toast && <div className="toast">✓ {toast}</div>}
    {modal === 'employee' && <Modal title="직원 등록" onClose={() => setModal(null)}><form onSubmit={saveEmployee}><label>이름<input name="name" placeholder="직원 이름" autoFocus required/></label><div className="form-row"><label>부서<input name="team" placeholder="예: 매장팀"/></label><label>직책<input name="role" placeholder="예: 바리스타"/></label></div><label>급여 형태<select name="pay" defaultValue="시급제"><option>시급제</option><option>월급제</option><option>일급제</option></select></label><button className="submit">등록 완료</button></form></Modal>}
    {modal === 'leave' && <Modal title="휴가 요청 검토" onClose={() => setModal(null)}><div className="request-detail"><Avatar name="이준호" color="purple"/><div><b>이준호님의 연차 신청</b><p>8월 14일 금요일 · 연차 1일</p></div></div><label className="note">관리자 메모<textarea placeholder="승인 메모를 남길 수 있어요."/></label><div className="modal-actions"><button className="reject" onClick={() => {setModal(null);setToast('요청을 반려했어요.')}}>반려</button><button className="submit" onClick={approve}>승인하기</button></div></Modal>}
    {modal === 'leaveRequest' && <Modal title="휴가 신청" onClose={() => setModal(null)}><form onSubmit={e => {e.preventDefault();setModal(null);setToast('휴가 신청을 보냈어요. 관리자 승인 후 반영됩니다.')}}><label>휴가 종류<select defaultValue="연차"><option>연차</option><option>오전 반차</option><option>오후 반차</option><option>시간 휴가</option></select></label><div className="form-row"><label>시작일<input type="date" defaultValue="2026-08-14" required/></label><label>종료일<input type="date" defaultValue="2026-08-14" required/></label></div><label>사유 (선택)<textarea placeholder="휴가 사유를 간단히 남겨 주세요."/></label><button className="submit">휴가 신청하기</button></form></Modal>}
    {modal === 'schedule' && <Modal title="근무 일정 추가" onClose={() => setModal(null)}><form onSubmit={e => {e.preventDefault();setModal(null);setToast('근무 일정을 추가했어요.')}}><label>직원<select defaultValue="김민지"><option>김민지</option><option>이준호</option><option>박서연</option></select></label><div className="form-row"><label>시작 시간<input type="time" defaultValue="09:00"/></label><label>종료 시간<input type="time" defaultValue="18:00"/></label></div><button className="submit">일정 저장</button></form></Modal>}
    {modal === 'attendance' && <Modal title="오늘 출퇴근 현황" onClose={() => setModal(null)}><p className="modal-text">총 23명 중 18명이 출근했습니다. 미출근 직원 2명과 지각 직원 1명을 확인해 주세요.</p><button className="submit" onClick={() => {setModal(null);setActive('attendance')}}>출퇴근 관리로 이동</button></Modal>}
    {modal === 'more' && <Modal title="관리 메뉴" onClose={() => setModal(null)}><div className="more-menu">{nav.slice(3).map(([id, label, icon]) => <button key={id} onClick={() => {setModal(null);setActive(id)}}><i>{icon}</i><span>{label}</span><b>›</b></button>)}</div></Modal>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
