const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=v=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(Number(v)||0);
const mins=v=>{const n=Math.max(0,Math.round(Number(v)||0));return `${Math.floor(n/60)}시간 ${n%60}분`;};
const type=v=>({hourly:'시급제',daily:'일급제',monthly:'월급제',annual:'연봉제'}[v]||v||'-');
const colors=['#2563EB','#DC2626','#059669','#7C3AED','#D97706','#0891B2','#DB2777','#4F46E5','#65A30D','#EA580C'];

export function openPayrollPrintView({rows,details,month,employeeId=null}){
  const targets=employeeId?rows.filter(row=>row.staffId===employeeId):rows;if(!targets.length)return false;
  const pages=targets.map((row,index)=>{const daily=details.filter(item=>item.staffId===row.staffId||item.name===row.name)
    .sort((a,b)=>String(a.date).localeCompare(String(b.date)));const overtime=daily.reduce((s,x)=>s+Number(x.overtimeMinutes||0),0);const totalBreak=daily.reduce((s,x)=>s+Number(x.breakMinutes||0),0);const deducted=daily.reduce((s,x)=>s+Number(x.deductedBreakMinutes||0),0);const body=daily.length?daily.map(x=>`<tr class="${x.overtimeMinutes?'overtime':''}"><td>${esc(x.date)}</td><td><b>${esc(x.shiftName)}</b><small>${esc(x.scheduledTime)}</small></td><td>${esc(x.actualTime)}</td><td>${mins(x.grossMinutes)}</td><td><span class="pill ${x.breakPaid?'paid':''}">${x.breakPaid?'급여 포함':'급여 미포함'}</span><small>${mins(x.breakMinutes)}</small></td><td>${mins(x.payableMinutes)}</td><td>${x.overtimeMinutes?`<strong>+${mins(x.overtimeMinutes)}</strong>`:'-'}</td><td>${x.dailyPay==null?'-':cash(x.dailyPay)}</td></tr>`).join(''):'<tr><td class="empty" colspan="8">퇴근 완료된 근태 기록이 없습니다.</td></tr>';return `<section class="page" style="--accent:${colors[index%colors.length]}"><header><div><span>TIMEFIT PAYROLL STATEMENT</span><h1>${esc(month.replace('-','년 '))}월 급여명세 초안</h1><p>스케줄과 실제 출퇴근 기록을 비교한 세전 검토 자료입니다.</p></div><aside><small>직원</small><b>${esc(row.name)}</b><em>${type(row.payType)}</em></aside></header><div class="cards"><article><span>지급 예정액</span><b>${cash(row.estimatedTotal)}</b><small>세금·공제 전</small></article><article><span>적용 단가</span><b>${cash(row.rate)}</b><small>${type(row.payType)}</small></article><article><span>급여 계산시간</span><b>${mins(row.workedMinutes)}</b><small>실제 출퇴근 기준</small></article><article><span>초과근무</span><b>${mins(overtime)}</b><small>${daily.filter(x=>x.overtimeMinutes).length}일 발생</small></article></div><div class="breaks"><b>휴게시간 처리</b><span>등록 ${mins(totalBreak)}</span><span>급여 미포함 차감 ${mins(deducted)}</span><span>유급 휴게 ${daily.filter(x=>x.breakPaid&&x.breakMinutes).length}일</span></div><h2>날짜별 근태·급여 산정 상세</h2><table><thead><tr><th>날짜</th><th>스케줄</th><th>실제 출퇴근</th><th>체류시간</th><th>휴게 처리</th><th>급여시간</th><th>초과근무</th><th>일별 급여</th></tr></thead><tbody>${body}</tbody></table><footer><span>실제 퇴근 완료 기록 · 스케줄별 유급/무급 휴게 · 운영 설정 반올림 기준</span><b>${index+1} / ${targets.length}</b></footer></section>`;}).join('');
  const popup=window.open('','_blank');if(!popup)return false;popup.opener=null;popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>급여명세_${esc(month)}</title><style>@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}body{margin:0;background:#eef2f7;color:#191f28;font-family:-apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo","Noto Sans KR",sans-serif}.page{width:277mm;min-height:190mm;margin:16px auto;padding:12mm;border-top:7px solid var(--accent);border-radius:14px;background:#fff;box-shadow:0 8px 28px #1e293b18;page-break-after:always}.page:last-child{page-break-after:auto}header{display:flex;justify-content:space-between;padding-bottom:7mm;border-bottom:1px solid #dfe5ec}header span{color:var(--accent);font-size:9px;font-weight:900;letter-spacing:1.4px}h1{margin:3px 0 5px;font-size:24px}header p{margin:0;color:#6b7684;font-size:10px}aside{min-width:52mm;padding:10px 14px;border:1px solid #dfe5ec;border-left:5px solid var(--accent);border-radius:10px}aside small,aside b,aside em{display:block}aside b{margin:3px 0;font-size:17px}aside em{color:#6b7684;font-size:9px;font-style:normal}.cards{display:grid;grid-template-columns:1.35fr repeat(3,1fr);gap:8px;margin:7mm 0 4mm}.cards article{padding:11px;border:1px solid #e5e8eb;border-radius:10px;background:#f8fafc}.cards article:first-child{background:color-mix(in srgb,var(--accent) 7%,white)}.cards span,.cards small{display:block;color:#6b7684;font-size:8px}.cards b{display:block;margin:5px 0 3px;font-size:16px}.breaks{display:flex;gap:18px;padding:9px 12px;border-radius:9px;background:#f2f4f6;font-size:9px}h2{margin:6mm 0 3mm;font-size:13px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:8px}th{padding:7px 5px;background:#e9eef5;color:#4e5968;text-align:left}td{padding:6px 5px;border-bottom:1px solid #edf0f3}td b,td small{display:block}td small{margin-top:2px;color:#8b95a1;font-size:7px}.pill{display:inline-block;padding:3px 5px;border-radius:5px;background:#fff0e5;color:#d65f00;font-weight:800}.pill.paid{background:#e7f7ef;color:#087a4f}.overtime td{background:#fffaf0}.overtime td:nth-child(7) strong{color:#d65f00}.empty{text-align:center;padding:20px;color:#8b95a1}footer{display:flex;justify-content:space-between;margin-top:5mm;padding-top:3mm;border-top:1px solid #dfe5ec;color:#8b95a1;font-size:8px}.print{position:fixed;right:22px;bottom:22px;padding:13px 18px;border:0;border-radius:11px;background:#3182f6;color:white;font-weight:800;cursor:pointer}@media print{body{background:white}.page{width:auto;min-height:0;margin:0;padding:0;border-radius:0;box-shadow:none}.print{display:none}}</style></head><body>${pages}<button class="print" onclick="window.print()">PDF 저장 · 인쇄</button></body></html>`);popup.document.close();return true;
}
